"""add is_calculated field to Score table

Revision ID: 38ca2ff82611
Revises: 660f639ac18a
Create Date: 2025-11-30 13:32:21.806332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ca2ff82611'
down_revision = '660f639ac18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_calculated', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('is_calculated')

    # ### end Alembic commands ###
