"""add hide field to BackgroundTask

Revision ID: 4ebb572977c9
Revises: 6510b2581cbb
Create Date: 2025-10-26 16:29:48.383645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebb572977c9'
down_revision = '6510b2581cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hide', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_column('hide')

    # ### end Alembic commands ###
