"""update to SQLAlchemy 2.0

Revision ID: 51d4ec993033
Revises: f05d42acf190
Create Date: 2025-06-01 22:25:21.793175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51d4ec993033'
down_revision = 'f05d42acf190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exams')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')

    op.drop_table('users')
    op.drop_table('user_exams')
    op.drop_table('students')
    op.drop_table('subjects')
    op.drop_table('scores')
    op.drop_table('zhixue_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zhixue_users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('zhixue_users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('cookie', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='zhixue_users_pkey'),
    sa.UniqueConstraint('username', name='zhixue_users_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('exam_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('class_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('class_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('school_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name='scores_exam_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='scores_student_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='scores_subject_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scores_pkey')
    )
    op.create_table('subjects',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='subjects_pkey'),
    sa.UniqueConstraint('id', name='subjects_id_key')
    )
    op.create_table('students',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='students_pkey'),
    sa.UniqueConstraint('id', name='students_id_key')
    )
    op.create_table('user_exams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('zhixue_username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('exam_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name='user_exams_exam_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_exams_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('registration_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('last_login_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('zhixue_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['zhixue_account_id'], ['zhixue_users.id'], name='users_zhixue_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email', ['email'], unique=True)

    op.create_table('exams',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='exams_pkey'),
    sa.UniqueConstraint('id', name='exams_id_key')
    )
    # ### end Alembic commands ###
