"""add email verification

Revision ID: 6510b2581cbb
Revises: 6fb6951200c9
Create Date: 2025-10-12 19:22:15.495506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6510b2581cbb'
down_revision = '6fb6951200c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 为没有邮箱的用户设置占位邮箱
    # 使用 username@placeholder.local 格式
    op.execute("""
        UPDATE users
        SET email = username || '@placeholder.local'
        WHERE email IS NULL OR email = ''
    """)

    # 添加新字段
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token_expires', sa.DateTime(), nullable=True))

    # 为现有用户设置 email_verified 为 True（向后兼容）
    op.execute("UPDATE users SET email_verified = true WHERE email_verified IS NULL")

    # 将 email_verified 改为非空约束，并设置 email 为必填
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_verified',
               existing_type=sa.Boolean(),
               nullable=False,
               server_default='false')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 将 email 和 email_verified 改回可空
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('email_verified',
               existing_type=sa.Boolean(),
               nullable=True,
               server_default=None)

    # 删除邮件验证相关字段
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verification_token_expires')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified')

    # 清理占位邮箱，设为 NULL
    op.execute("""
        UPDATE users
        SET email = NULL
        WHERE email LIKE '%@placeholder.local'
    """)

    # ### end Alembic commands ###
