"""support multi-school exams with exam_schools table

Revision ID: 660f639ac18a
Revises: 4ebb572977c9
Create Date: 2025-11-02 13:34:37.548978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660f639ac18a'
down_revision = '4ebb572977c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_schools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.String(length=50), nullable=False),
    sa.Column('school_id', sa.String(length=50), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'school_id')
    )
    with op.batch_alter_table('exam_schools', schema=None) as batch_op:
        batch_op.create_index('ix_exam_schools_exam', ['exam_id'], unique=False)
        batch_op.create_index('ix_exam_schools_school', ['school_id'], unique=False)

    # 从 Exam 表复制数据到 ExamSchool 表
    connection = op.get_bind()
    result = connection.execute(sa.text(
        "SELECT id, school_id, is_saved FROM exams WHERE school_id IS NOT NULL"
    ))
    for exam_id, school_id, is_saved in result:
        connection.execute(sa.text(
            "INSERT INTO exam_schools (exam_id, school_id, is_saved) VALUES (:exam_id, :school_id, :is_saved)"
        ), {"exam_id": exam_id, "school_id": school_id, "is_saved": is_saved})

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.String(length=50), nullable=True))

    # 从 Exam.school_id 复制到 Score.school_id
    connection.execute(sa.text(
        "UPDATE scores SET school_id = (SELECT school_id FROM exams WHERE exams.id = scores.exam_id)"
    ))

    # 将 school_id 设置为 NOT NULL
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_index('ix_scores_exam_school', ['exam_id', 'school_id'], unique=False)
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_school_id', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['manual_school_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('manual_school_id')

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_scores_exam_school')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('exam_schools', schema=None) as batch_op:
        batch_op.drop_index('ix_exam_schools_school')
        batch_op.drop_index('ix_exam_schools_exam')

    op.drop_table('exam_schools')
    # ### end Alembic commands ###
