"""add indexes

Revision ID: 6fb6951200c9
Revises: c46e6498afc0
Create Date: 2025-10-05 21:30:16.164532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb6951200c9'
down_revision = 'c46e6498afc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_background_tasks_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_background_tasks_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_background_tasks_uuid_user', ['uuid', 'user_id'], unique=False)
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index('ix_exams_created', ['created_at'], unique=False)
        batch_op.create_index('ix_exams_school_created', ['school_id', 'created_at'], unique=False)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index('ix_scores_exam_sort', ['exam_id', 'sort'], unique=False)
        batch_op.create_index('ix_scores_exam_student', ['exam_id', 'student_id'], unique=False)

    with op.batch_alter_table('user_exams', schema=None) as batch_op:
        batch_op.create_index('ix_user_exams_zhixue_exam', ['zhixue_id', 'exam_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('zhixue_student_accounts', schema=None) as batch_op:
        batch_op.create_index('ix_zhixue_student_accounts_school', ['school_id'], unique=False)

    with op.batch_alter_table('zhixue_teacher_accounts', schema=None) as batch_op:
        batch_op.create_index('ix_zhixue_teacher_accounts_school', ['school_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zhixue_teacher_accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_zhixue_teacher_accounts_school')

    with op.batch_alter_table('zhixue_student_accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_zhixue_student_accounts_school')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    with op.batch_alter_table('user_exams', schema=None) as batch_op:
        batch_op.drop_index('ix_user_exams_zhixue_exam')

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index('ix_scores_exam_student')
        batch_op.drop_index('ix_scores_exam_sort')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index('ix_exams_school_created')
        batch_op.drop_index('ix_exams_created')

    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('ix_background_tasks_uuid_user')
        batch_op.drop_index('ix_background_tasks_user_created')
        batch_op.drop_index('ix_background_tasks_status_created')

    # ### end Alembic commands ###
