"""add is_public column to exam_schools table

Revision ID: 871b0ffe63a9
Revises: 9b2ca8a0ff05
Create Date: 2026-09-13 18:51:06.404236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871b0ffe63a9'
down_revision = '9b2ca8a0ff05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_schools', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
