"""add sort in scores

Revision ID: 8f207c221c7c
Revises: 8a8ae69f04e6
Create Date: 2025-08-23 14:52:19.543879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f207c221c7c'
down_revision = '8a8ae69f04e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort', sa.Integer(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('sort')

    # ### end Alembic commands ###
