"""add subject_name in scores

Revision ID: 97044c08487c
Revises: f9a2cb7e36f3
Create Date: 2025-08-23 10:53:25.526054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97044c08487c'
down_revision = 'f9a2cb7e36f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('subject_name')

    # ### end Alembic commands ###
