"""add support for assigned scores

Revision ID: 9b2ca8a0ff05
Revises: 4a4620974d1e
Create Date: 2026-04-10 23:56:02.085664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2ca8a0ff05'
down_revision = '4a4620974d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_assign', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('origin_score', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('origin_score')
        batch_op.drop_column('is_assign')

    # ### end Alembic commands ###
