"""clean up indexes

Revision ID: a3f0f217940b
Revises: 38ca2ff82611
Create Date: 2026-02-14 13:53:50.523262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f0f217940b'
down_revision = '38ca2ff82611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_tasks_uuid_user'))

    with op.batch_alter_table('exam_schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_schools_exam'))

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_school_created'))

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_exam_sort'))
        batch_op.create_index('ix_scores_exam_class', ['exam_id', 'class_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index('ix_scores_exam_class')
        batch_op.create_index(batch_op.f('ix_scores_exam_sort'), ['exam_id', 'sort'], unique=False)

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_school_created'), ['school_id', 'created_at'], unique=False)

    with op.batch_alter_table('exam_schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_schools_exam'), ['exam_id'], unique=False)

    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_tasks_uuid_user'), ['uuid', 'user_id'], unique=False)

    # ### end Alembic commands ###
