"""add permissions in users table

Revision ID: c46e6498afc0
Revises: 8f207c221c7c
Create Date: 2025-09-21 18:49:47.268815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46e6498afc0'
down_revision = '8f207c221c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###

    # 数据迁移：为现有用户设置权限
    # admin 用户设置为 33333 (全局权限)
    op.execute("UPDATE users SET permissions = '33333' WHERE role = 'admin'")

    # user 用户设置为 10110 (基础权限)
    op.execute("UPDATE users SET permissions = '10110' WHERE role = 'user'")

    # data_viewer 用户改为 user 角色，设置为 11112 (数据查看权限)
    op.execute("UPDATE users SET role = 'user', permissions = '11112' WHERE role = 'data_viewer'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###
