"""add is_parent to zhixue_student_accounts

Revision ID: ccfc91a0b3c9
Revises: f1af8f43beff
Create Date: 2026-02-24 15:52:33.461791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfc91a0b3c9'
down_revision = 'f1af8f43beff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zhixue_student_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_parent', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zhixue_student_accounts', schema=None) as batch_op:
        batch_op.drop_column('is_parent')

    # ### end Alembic commands ###
