"""remove deprecated columns

Revision ID: d8c20202f147
Revises: a3f0f217940b
Create Date: 2026-02-14 14:16:34.376539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c20202f147'
down_revision = 'a3f0f217940b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('exams_school_id_fkey'), type_='foreignkey')
        batch_op.drop_column('is_saved')
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_saved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('exams_school_id_fkey'), 'schools', ['school_id'], ['id'])

    # ### end Alembic commands ###
