"""save encrypted zhixue passwords

Revision ID: f1af8f43beff
Revises: d8c20202f147
Create Date: 2026-02-20 20:45:49.431559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1af8f43beff'
down_revision = 'd8c20202f147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zhixue_student_accounts', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('zhixue_teacher_accounts', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)

    from app.utils.crypto import encrypt

    conn = op.get_bind()
    for table in ['zhixue_student_accounts', 'zhixue_teacher_accounts']:
        rows = conn.execute(sa.text(f'SELECT id, password, cookie FROM {table}')).fetchall()
        for row in rows:
            conn.execute(
                sa.text(f'UPDATE {table} SET password = :password, cookie = :cookie WHERE id = :id'),
                {'id': row.id, 'password': encrypt(row.password), 'cookie': encrypt(row.cookie)}
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from app.utils.crypto import decrypt

    conn = op.get_bind()
    for table in ['zhixue_student_accounts', 'zhixue_teacher_accounts']:
        rows = conn.execute(sa.text(f'SELECT id, password, cookie FROM {table}')).fetchall()
        for row in rows:
            conn.execute(
                sa.text(f'UPDATE {table} SET password = :password, cookie = :cookie WHERE id = :id'),
                {'id': row.id, 'password': decrypt(row.password), 'cookie': decrypt(row.cookie)}
            )

    with op.batch_alter_table('zhixue_teacher_accounts', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('zhixue_student_accounts', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
