"""remove subjects

Revision ID: f9a2cb7e36f3
Revises: 59bc834850cd
Create Date: 2025-08-23 09:50:38.641167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a2cb7e36f3'
down_revision = '59bc834850cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('scores_subject_id_fkey'), type_='foreignkey')

    op.drop_table('subjects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('subjects_pkey')),
    sa.UniqueConstraint('id', name=op.f('subjects_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('scores_subject_id_fkey'), 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###
