"""add realname

Revision ID: f9f74ce37f23
Revises: db1b8daea843
Create Date: 2025-06-22 17:24:40.680866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f74ce37f23'
down_revision = 'db1b8daea843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zhixue_teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realname', sa.String(length=80), nullable=False))

    with op.batch_alter_table('zhixue_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realname', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zhixue_users', schema=None) as batch_op:
        batch_op.drop_column('realname')

    with op.batch_alter_table('zhixue_teachers', schema=None) as batch_op:
        batch_op.drop_column('realname')

    # ### end Alembic commands ###
